### ISSUE TITLE
TypeError: winston_loki_1.default is not a constructor

### ISSUE THREAD

**Issue by vothanhbinhlt** [JaniAnttonen/winston-loki#121]
Hello there, I am using this module with Nestjs. I have a problem

```
npm run start:dev                                                                                                                                       4s  14.20.1  17:15:07

> devpanel-api-v2@0.0.1 start:dev /Users/binhvo/Workspaces/devpanel/uiv4backend-v2
> nest start --watch
[5:15:38 PM] Starting compilation in watch mode...

[5:15:57 PM] Found 0 errors. Watching for file changes.


/Users/binhvo/Workspaces/devpanel/uiv4backend-v2/src/app.module.ts:58
        new LokiTransport({
        ^
TypeError: winston_loki_1.default is not a constructor
    at Object.<anonymous> (/Users/binhvo/Workspaces/devpanel/uiv4backend-v2/src/app.module.ts:58:9)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/binhvo/Workspaces/devpanel/uiv4backend-v2/src/main.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

**Comment by VipinGoyal** [comment]
You might be importing it via import instead of require. In order to avoid this, I was able to solve this issue by adding this 

"esModuleInterop": true 
in tsconfig.json and 
then this worked for me
import LokiTransport from 'winston-loki';
